version: '3.4'

services:
  client:
    image: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
